### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by joristork** [marians/openweather#10]
Hi -- openweather crashed for me, both under python3 and python2.7, and both from the command line and the example script, e.g.:
Joriss-MBPR:Desktop joris$ openweather -s 4885
OpenWeather.do_request() got unknown exception: <class 'AttributeError'> (1. attempt)
OpenWeather.do_request() got unknown exception: <class 'AttributeError'> (2. attempt)
OpenWeather.do_request() got unknown exception: <class 'AttributeError'> (3. attempt)
Traceback (most recent call last):
  File "/usr/local/bin/openweather", line 9, in <module>
    load_entry_point('openweather==0.11', 'console_scripts', 'openweather')()
  File "/usr/local/lib/python3.4/site-packages/openweather.py", line 232, in main
    print(json.dumps(flatten_dict(weather), indent=4, sort_keys=True))
  File "/usr/local/lib/python3.4/site-packages/openweather.py", line 154, in flatten_dict
    for k, v in d.items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by Zenock** [comment]
Two things that could be related.  

1. openweather uses the base URL 'http://openweathermap.org/data/2.1'  I don't think this path exists any more.  I mean put this in your browser... 

http://openweathermap.org/data/2.1/weather/station/4885?type=json

it returns a 404 error.

So code is could be outdated.

**Comment by marians** [comment]
Thanks for the report. Yes, as @Zenock says, OpenWeatherMap discontinued API version 2.1.

I started exploring if it's possible to update to the latest API version (2.5) in the branch `api-version-2-5` with the in-progress pull request https://github.com/marians/openweather/pull/11.

See my comments there about what I think the current problem is.

**Comment by Zenock** [comment]
Ack... My grammar on that post suffered terribly.  Also never got around to my second point.

Second point.  I think the new API requires you sign up for a "API key".  Although in playing around with it, it isn't completely clear when the key is necessary.  I've been able to pull some data without it.  But other times I've had to have it.  All rather confusing.
